groups:
- name: slo-events-over-time-4w--interval-3m
  interval: 3m
  rules:
     - record: slo:events_over_time
       expr: last_over_time(slo:events_over_time:sparse{slo_time_range="4w"}[30m])

#
# 4w aggregation may be quite resource-intensive for the monitoring stack, so we evaluate it just once every 15 minutes.
# This causes slo:events_over_time:sparse timeseries to be discontinuous making it most probably useless to be used directly unless last_over_time is applied.
#
# Sharded into 2 queries based on namespace to lower computational intensity
- name: slo-events-over-time-4w--interval-15m-production
  interval: 15m
  rules:
     - record: slo:events_over_time:sparse
       labels:
         slo_time_range: 4w
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total{namespace="production"}[4w])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)
- name: slo-events-over-time-4w--interval-15m-not-production
  interval: 15m
  rules:
     - record: slo:events_over_time:sparse
       labels:
         slo_time_range: 4w
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total{namespace!="production"}[4w])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)


- name: slo-events-over-time-3d--interval-3m
  interval: 3m
  rules:
     - record: slo:events_over_time
       labels:
         slo_time_range: 3d
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total[3d])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)

- name: slo-events-over-time-1d--interval-3m
  interval: 3m
  rules:
     - record: slo:events_over_time
       labels:
         slo_time_range: 1d
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total[1d])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)

- name: slo-events-over-time-6h--interval-3m
  interval: 3m
  rules:
     - record: slo:events_over_time
       labels:
         slo_time_range: 6h
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total[6h])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)

- name: slo-events-over-time-2h--interval-3m
  interval: 3m
  rules:
     - record: slo:events_over_time
       labels:
         slo_time_range: 2h
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total[2h])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)

- name: slo-events-over-time--interval-1m
  interval: 1m
  rules:
     - record: slo:events_over_time
       labels:
         slo_time_range: 1h
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total[1h])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)
     - record: slo:events_over_time
       labels:
         slo_time_range: 30m
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total[30m])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)
     - record: slo:events_over_time
       labels:
         slo_time_range: 5m
       expr:
            sum(
                increase(slo_domain_slo_class:slo_events_total[5m])
            ) by (slo_class, slo_domain, slo_version, slo_type, result, namespace)
