groups:
  - name: slo-events-rate-coefficient
    # every slo:events_rate_coefficient is multiplied by a constant which normalizes the difference of time_ranges
    # it is needed because slo:events_over_time is computed using increase rather than rate (in which case this wouldn't be needed)
    interval: 3m
    rules:
      - record: slo:events_rate_coefficient
        expr: |
            (sum(slo:events_over_time{slo_time_range="1h"}) without (result) * 24*28 )
            / on(slo_version, slo_domain, slo_class, slo_type, namespace) group_left()
            sum(slo:events_over_time{slo_time_range="4w"}) without (result)
        labels:
          slo_time_range: 1h

      - record: slo:events_rate_coefficient
        expr: |
            (sum(slo:events_over_time{slo_time_range="6h"}) without (result) * 4*28 )
            / on(slo_version, slo_domain, slo_class, slo_type, namespace) group_left()
            sum(slo:events_over_time{slo_time_range="4w"}) without (result)
        labels:
          slo_time_range: 6h

      - record: slo:events_rate_coefficient
        expr: |
            (sum(slo:events_over_time{slo_time_range="1d"}) without (result) * 28 )
            / on(slo_version, slo_domain, slo_class, slo_type, namespace) group_left()
            sum(slo:events_over_time{slo_time_range="4w"}) without (result)
        labels:
          slo_time_range: 1d

      - record: slo:events_rate_coefficient
        expr: |
            (sum(slo:events_over_time{slo_time_range="3d"}) without (result) * 28/3 )
            / on(slo_version, slo_domain, slo_class, slo_type, namespace) group_left()
            sum(slo:events_over_time{slo_time_range="4w"}) without (result)
        labels:
          slo_time_range: 3d
